#!/bin/bash
# Icon Generation Script for BD & Associates Inventory Manager
# This script helps set up the app icon using your BD & Associates logo

echo "=== BD & Associates Inventory Manager - Icon Setup ==="
echo ""
echo "To set up your app icon with the BD & Associates logo:"
echo ""
echo "OPTION 1 - Using Android Studio (Easiest):"
echo "1. Open your Android project in Android Studio"
echo "2. Right-click on 'app' folder in Project view"
echo "3. Select 'New' → 'Image Asset'"
echo "4. Choose 'Launcher Icons (Adaptive and Legacy)'"
echo "5. Set Asset Type to 'Image'"
echo "6. Click the folder icon next to 'Path'"
echo "7. Browse and select your BD & Associates logo file"
echo "8. Adjust the scaling and padding as needed"
echo "9. Click 'Next' then 'Finish'"
echo ""
echo "OPTION 2 - Manual Setup:"
echo "1. Prepare your BD & Associates logo as PNG files in these sizes:"
echo "   - 48x48 px (for mipmap-mdpi)"
echo "   - 72x72 px (for mipmap-hdpi)"
echo "   - 96x96 px (for mipmap-xhdpi)"
echo "   - 144x144 px (for mipmap-xxhdpi)"
echo "   - 192x192 px (for mipmap-xxxhdpi)"
echo ""
echo "2. Replace the ic_launcher.png files in these folders:"
echo "   android/app/src/main/res/mipmap-mdpi/ic_launcher.png"
echo "   android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
echo "   android/app/src/main/res/mipmap-xhdpi/ic_launcher.png"
echo "   android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png"
echo "   android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"
echo ""
echo "OPTION 3 - Online Generator:"
echo "1. Visit: https://appicon.co/"
echo "2. Upload your BD & Associates logo"
echo "3. Download the Android icon pack"
echo "4. Extract and copy the mipmap folders to your Android project"
echo ""
echo "After setting up icons:"
echo "1. Clean and rebuild your project"
echo "2. Run: npm run android:build"
echo "3. Test the app to see your new icon"
echo ""
echo "Your app will now display the BD & Associates logo as its icon!"
